server:
  port: 80

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://svc.gksl2.cloudtype.app:31617/ecommerce"
    username: ecommerce
    password: ecommerce
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: create
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug    # Logger
    org.hibernate.type: trace   # Show Query Parameter