server:
  port: 8081

url:
  prefix: /api
  version: /v1

spring:
  profiles:
    active: prod
  web:
    resources:
      static-locations: classpath:/static, classpath:/build
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://svc.gksl2.cloudtype.app:31617/ecommerce"
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: "jdbc:log4jdbc:mariadb://svc.gksl2.cloudtype.app:31617/ecommerce"
    username: ecommerce
    password: ecommerce
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        show_sql: true


logging:
  level:
    org.hibernate.SQL: debug    # Logger
    org.hibernate.type: trace   # Show Query Parameter
#    org.springframework.web: DEBUG
#    com.zaxxer.hikari.HikariDataSource: ERROR
